[var.swagho_synth_config]
swagho_issuance_ratio = "<%= MaxUint256 %>"
swagho_liquidation_ratio = "<%= parseEther('1.1') %>"
swagho_liquidation_reward = "<%= parseEther('1') %>"
swagho_min_delegation = "<%= parseEther('100') %>"

[invoke.configure_swagho_collateral]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "configureCollateral"  # "args" see below in the multiline block

[[invoke.configure_swagho_collateral.args]]
tokenAddress = "<%= extras.synth_wa_gho_token_address %>"
oracleNodeId = "<%= extras.erc_4626_to_assets_ratio_oracle_id %>"
issuanceRatioD18 = "<%= settings.swagho_issuance_ratio %>"
liquidationRatioD18 = "<%= settings.swagho_liquidation_ratio %>"
liquidationRewardD18 = "<%= settings.swagho_liquidation_reward %>"
minDelegationD18 = "<%= settings.swagho_min_delegation %>"
depositingEnabled = true
