[setting.synthWaGHOMaxMarketCollateral]
defaultValue = "<%= parseEther(String(50_000_000)) %>"

[setting.spotStrictStalenessTolerance]
defaultValue = "60"

[setting.wagho_issuance_ratio]
defaultValue = "<%= MaxUint256 %>"

[setting.wagho_liquidation_ratio]
defaultValue = "<%= parseEther('1.1') %>"

[setting.wagho_liquidation_reward]
defaultValue = "<%= parseEther('1') %>"

[setting.wagho_min_delegation]
defaultValue = "<%= parseEther('100') %>"

[invoke.SpotMarketProxy_createSynth_waGho]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "owner"
func = "createSynth"
args = ["Synthetic Static waGHO", "sWaGHO", "<%= settings.pdao %>"]
extra.synth_wa_gho_market_id.event = "SynthRegistered"
extra.synth_wa_gho_market_id.arg = 0
extra.synth_wa_gho_token_address.event = "SynthRegistered"
extra.synth_wa_gho_token_address.arg = 1
depends = ['invoke.allowPdaoToCreateSynth']

[invoke.SpotMarketProxy_updatePriceData_waGho]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_wa_gho_market_id %>"]
func = "updatePriceData"
args = [
    "<%= extras.synth_wa_gho_market_id %>",
    "<%= extras.erc_4626_to_assets_ratio_oracle_id %>",
    "<%= extras.erc_4626_to_assets_ratio_oracle_id %>",
    "<%= settings.spotStrictStalenessTolerance %>",     # Effectively unused, as this oracle node will never return something stale
]

[invoke.CoreProxy_configureMaximumMarketCollateral_waGho]
target = ["system.CoreProxy"]
fromCall.func = "owner"
fromCall.args = []
func = "configureMaximumMarketCollateral"
args = [
    "<%= extras.synth_wa_gho_market_id %>",
    "<%= settings.waBasGHO_address %>",
    "<%= settings.synthWaGHOMaxMarketCollateral %>",
]

[invoke.SpotMarketProxy_setWrapper_waGho]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_wa_gho_market_id %>"]
func = "setWrapper"
args = [
    "<%= extras.synth_wa_gho_market_id %>",
    "<%= settings.waBasGHO_address %>",
    "<%= settings.synthWaGHOMaxMarketCollateral %>",
]

# We allow waGHO as collateral with depositingEnabled = false so the spot market can deposit it, but it can't be LPed
# Users deposit/delegate sWaGHO
[invoke.CoreProxy_configureCollateral_waGho]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "configureCollateral"  # "args" see below in the multiline block

[[invoke.CoreProxy_configureCollateral_waGho.args]]
tokenAddress = "<%= settings.waBasGHO_address %>"
oracleNodeId = "<%= extras.erc_4626_to_assets_ratio_oracle_id %>"
issuanceRatioD18 = "<%= settings.wagho_issuance_ratio %>"
liquidationRatioD18 = "<%= settings.wagho_liquidation_ratio %>"
liquidationRewardD18 = "<%= settings.wagho_liquidation_reward  %>"
minDelegationD18 = "<%= settings.wagho_min_delegation %>"
depositingEnabled = false
